LineLength:
  Max: 120
AllCops:
  Exclude:
    - 'doorkeeper/**/*'
    - 'spec/**/*'
  DisplayCopNames: true
Documentation:
  Enabled: false
Layout/EndOfLine:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - lib/doorkeeper/orm/sequel/validators/*
    - lib/doorkeeper-sequel/generators/templates*

Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: true

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/SymbolArray:
  MinSize: 3
Style/WordArray:
  MinSize: 3
Style/NumericPredicate:
  Enabled: false
Style/DoubleNegation:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/TrailingBlankLines:
  Enabled: true
Layout/DotPosition:
  EnforcedStyle: leading