LineLength:
  Max: 120
AllCops:
  Exclude:
    - 'doorkeeper/**/*'
    - 'spec/**/*'
  DisplayCopNames: true
Rails:
  Enabled: true
Documentation:
  Enabled: false
Layout/EndOfLine:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - lib/doorkeeper/orm/sequel/validators/*
    - lib/doorkeeper-sequel/generators/templates*
