language: ruby
sudo: false
cache: bundler
bundler_args: --without yard guard benchmarks

before_install:
  - gem install bundler -v '~> 1.10'

gemfile:
  - gemfiles/rails-4.2.gemfile
  - gemfiles/rails-5.0.gemfile
  - gemfiles/rails-5.1.gemfile
  - gemfiles/rails-5.2.gemfile

rvm:
  - 2.1
  - 2.2.4
  - 2.3.3
  - 2.4.1
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
  exclude:
    - rvm: 2.1
      gemfile: gemfiles/rails-5.0.gemfile
    - rvm: 2.1
      gemfile: gemfiles/rails-5.1.gemfile
    - rvm: 2.1
      gemfile: gemfiles/rails-5.2.gemfile
